### ISSUE TITLE
Problem when getting or editing configuration

### ISSUE THREAD

**Issue by festradasolano** [openvswitch/of-config#21] opened 2015-05-30 20:54 UTC
Hi. I'm getting a very weird error when trying to get or edit configuration from netopeer-cli. Please, some help.

**The connection process is OK.**

CLIENT

```
netconf> connect --login ubuntu localhost
ubuntu@localhost password:
netconf>
```

OFC-SERVER

```
ofc-server[1396]: Some message received
ofc-server[1396]: Sending capabilities to agent.
ofc-server[1396]: Some message received
ofc-server[1396]: Created dummy session 1 for user 'ubuntu' (UID 1000)
ofc-server[1396]: New agent ID set to :1.13 (PID 1479, NCSID 1)
```

**Error when trying to get running configuration**

CLIENT

```
netconf> get-config running
NETCONF error: operation-failed (application) - Some unspecified error occurred.
netconf>
```

OFC-SERVER

```
ofc-server[1396]: Some message received
ofc-server[1396]: *_rpc_build: Missing <source> parameter of the RPC operation.
ofc-server[1396]: Processing request <?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <get-config>
    <source>
      <running/>
    </source>
  </get-config>
</rpc>
ofc-server[1396]: ncds_apply_rpc2all: invalid parameter rpc
```

**Error when trying to edit running configuration**

CLIENT

```
netconf> edit-config --config=create_port_eth1.xml running
NETCONF error: operation-failed (application) - Some unspecified error occurred.
netconf>
```

OFC-SERVER

```
ofc-server[1396]: Some message received
ofc-server[1396]: *_rpc_build: Missing <target> parameter of the RPC operation.
ofc-server[1396]: Processing request <?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
      <capable-switch xmlns="urn:onf:config:yang" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
        <id>openvswitch</id>
        <resources>
          <port nc:operation="create">
            <name>eth1</name>
            <requested-number>100</requested-number>
            <configuration>
              <admin-state>up</admin-state>
              <no-receive>false</no-receive>
              <no-forward>false</no-forward>
              <no-packet-in>false</no-packet-in>
            </configuration>
          </port>
        </resources>
        <logical-switches>
          <switch>
            <id>ofc-bridge</id>
            <resources>
              <port nc:operation="create">eth1</port>
            </resources>
          </switch>
        </logical-switches>
      </capable-switch>
    </config>
  </edit-config>
</rpc>
ofc-server[1396]: ncds_apply_rpc2all: invalid parameter rpc
```

I thought that this could be caused because of the version of **libnetconf**, so I checked out the branch **0.9.x** of libnetconf and installed everything again. But when I tried to install the ofc-server (make), I got a more weird error:

```
...
netconf-server-transapi.c:380:20: warning: initialization from incompatible pointer type [enabled by default]
                    .func = callback_srv_netconf_srv_ssh_srv_listen_oneport},
                    ^
netconf-server-transapi.c:380:20: warning: (near initialization for ‘server_clbks.callbacks[0].func’) [enabled by default]
netconf-server-transapi.c:382:20: warning: initialization from incompatible pointer type [enabled by default]
                    .func = callback_srv_netconf_srv_ssh_srv_listen_manyports},
                    ^
netconf-server-transapi.c:382:20: warning: (near initialization for ‘server_clbks.callbacks[1].func’) [enabled by default]
netconf-server-transapi.c:384:20: warning: initialization from incompatible pointer type [enabled by default]
                    .func = callback_srv_netconf_srv_ssh_srv_listen},
                    ^
netconf-server-transapi.c:384:20: warning: (near initialization for ‘server_clbks.callbacks[2].func’) [enabled by default]
netconf-server-transapi.c:403:5: error: unknown field ‘version’ specified in initializer
     .version = 6,
     ^
netconf-server-transapi.c:403:5: warning: initialization makes pointer from integer without a cast [enabled by default]
netconf-server-transapi.c:403:5: warning: (near initialization for ‘server_transapi.init’) [enabled by default]
make[2]: *** [netconf-server-transapi.o] Error 1
make[2]: Leaving directory `/home/ubuntu/of-config/server'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ubuntu/of-config'
make: *** [all] Error 2
```

And to recover from this last error I had to reset the whole installation because when I compile and install again the **master** branch, running the ofc-server deploys this weird error:

```
ubuntu@ubuntu-sdn:~/of-config$ sudo ofc-server -v 5 -f
ofc-server[15073]: Shared memory key: -4
ofc-server[15073]: Shared memory ID: 0
ofc-server[15073]: ncds_features_parse: no feature definitions found in data model ietf-inet-types.
ofc-server[15073]: ncds_features_parse: no feature definitions found in data model ietf-yang-types.
ofc-server[15073]: ncds_features_parse: no feature definitions found in data model ietf-netconf-monitoring.
ofc-server[15073]: ncds_features_parse: no feature definitions found in data model ietf-netconf-notifications.
ofc-server[15073]: ncds_features_parse: no feature definitions found in data model nc-notifications.
ofc-server[15073]: ncds_features_parse: no feature definitions found in data model notifications.
ofc-server[15073]: ncds_features_parse: no feature definitions found in data model ietf-netconf-with-defaults.
ofc-server[15073]: ncds_features_parse: no feature definitions found in data model ietf-netconf-acm.
ofc-server[15073]: ncds_set_validation: Relax NG validator set (//var/lib/libnetconf//ietf-netconf-acm-data.rng)
ofc-server[15073]: ncds_set_validation: Schematron validator set (//var/lib/libnetconf//ietf-netconf-acm-schematron.xsl)
ofc-server[15073]: Datastore ietf-netconf-acm initiated with ID 8.
ofc-server[15073]: Checking the default Events stream path //var/lib/libnetconf//streams/.
ofc-server[15073]: ncds_features_parse: no feature definitions found in data model ietf-x509-cert-to-name.
ofc-server[15073]: ncds_new_transapi_static: Missing data callbacks in transAPI module description.
ofc-server[15073]: Creating ietf-netconf-server datastore failed.
```

Please, some help.

**Comment by rkrejci** [comment] 2015-05-31 10:00
Hi, sorry for the problems, it is caused by one (my) stupid patch in the libnetconf master branch :( Now it should be fixed and master branch should work for you. 

ofc-server is not compatible with the libnetconf's 0.9.x branch, so use the master branch only.

Your last issue is probably caused by libnetconf versioning - from the 0.9.x branch, you have installed version 0.9.2, but master branch is marked as 0.9.0 :( so you are probably still using the libnetconf from 0.9.x branch. Please check your lib dir (probably /usr/local/lib(64)/) that all libnetconf symlinks points to the newest (by time of creation) libnetconf so (it should be libnetconf.so.0.9.0).

Once again, sorry for the problems you have.

**Comment by festradasolano** [comment] 2015-06-01 15:02
Thanks! Issue solved! I updated **master** branch of **libnetconf**, ran installing process again, and everything worked. Awesome implementation!

**Closed as completed** 2015-06-02 04:56 UTC
